version: '3.1'


services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_USER: postgres
      POSTGRES_DB: library

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080